-- MySQL database schema
CREATE DATABASE IF NOT EXISTS mern_db;
USE mern_db;

-- Example table
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
